config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts
  as :account do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_account_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'account_registration'
  end


  resources :admin

  resources :categories , except: [:show,:index]

  get 'top/index'
  get 'top/', to: 'top#index'
  get 'top/:id', to: 'top#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_and_belongs_to_many :categories

    validates :title, presence: {message: 'は必須項目です'}
    validates :main, presence: {message: 'は必須項目です'}
    validates :my_date, presence: {message: 'は必須項目です'}
    validates :writer, presence: {message: 'は必須項目です'}

    mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :articles

    validates :name, presence: {message: 'は必須項目です'}
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_account!

  def index
    @articles = Article.all
    @categories = Category.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create article_params
    if @article.save then
      redirect_to '/osusume/admin/'
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update article_params
    if @article.save then
      redirect_to '/osusume/admin/'
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to '/osusume/admin/' 
  end

  private 
  def article_params
    params.require(:article).permit(:title, :main, :my_date, :intro, :status, :writer,{:category_ids=> []}, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_account!

  def new
    @category = Category.new
  end

  def create
    @category = Category.create category_params
    if @category.save then
      redirect_to '/osusume/admin'
    else
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update category_params
    if @category.save then
      redirect_to '/osusume/admin'
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to '/osusume/admin' 
  end

  private 
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @articles = Article.all.order('my_date desc')
    @categories = Category.all
  end

  def show
    @articles = Article.all
    @categories = Category.all
    @article = Article.find(params[:id])
    if @article.status == false then
      authenticate_account!
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/edit.html.erb
<h1>記事編集</h1>

<% if @article.errors.any? %>
<ul>
    <% @article.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @article,:url => {:action => :update} do |form| %>
<table>
    <tr>
    <th>タイトル</th>
    <td><%= form.text_field :title %></td>
    </tr>
    <tr>
    <th>ライター</th>
    <td><%= form.text_field :writer %></td>
    </tr>
    <tr>
    <th>投稿日時</th>
    <td><%= raw sprintf(form.date_select(
								:my_date,
								use_month_numbers: true,
								start_year:        Time.now.year,
								end_year:          Time.now.year+1,
								date_separator: '%s'),
						'年 ', '月 ') + '日' %></td>
    </tr>
    <tr>
    <th>記事内容</th>
    <td><%= form.cktext_area :main %></td>
    </tr>
    <th>紹介文</th>
    <td><%= form.text_area :intro %></td>
    <tr>
    <th>カテゴリー</th>
    <td><%= collection_check_boxes(:article, :category_ids, Category.all, :id, :name) do |b| %>
        <%= b.label { b.check_box + b.text } %>
        　<% end %>
        </td>
    </tr>
    <tr><th>サムネイル</th>
    <td>
    <% if @article.image? %>
    <%= image_tag @article.image.url ,:size => "360x200" %>
    <% end %>
    <%= form.file_field :image %>
    </td></tr>
    <tr><th>状態</th>
    <td><%= form.radio_button :status, 'f', :checked => "checked" %>下書き<%= form.radio_button :status, 't' %>公開</td></tr>
  <tr><th></th>
    <td><%= form.submit "送信" %></td></tr>
</table>
<% end %>

app/views/admin/index.html.erb
<h3><a href="/osusume/admin/new">記事作成</a></h3>
<h3><a href="/osusume/categories/new">カテゴリー作成</a></h3>

<h2>記事一覧</h2>

<table>
  <tr>
      <th>状態</th><th>タイトル</th><th>ライター</th><th>投稿日時</th><th>紹介文</th>
  </tr>
  <% @articles.each do |obj| %>
  <tr>
    <td><% if obj.status == true %>公開<% else %>下書き<% end %></td>
    <td><a href="/osusume/admin/<%= obj.id %>"><%= obj.title %></a></td>
    <td><%= obj.writer %></td>
    <td><%= obj.my_date.to_date %></td>
    <td><%= obj.intro %></td>
    <td><a href="/osusume/admin/<%= obj.id %>/edit">編集</a></td>
    <td><%= link_to '削除', admin_path(obj), method: :delete, data: { confirm: 'このデータを削除しますか?' } %></td>
  </tr>
  <% end %>
</table>


<h2>カテゴリ一覧</h2>

<table>
  <tr>
      <th>カテゴリ名</th>
  </tr>
  <% @categories.each do |obj| %>
  <tr>
    <td><%= obj.name %></td>
    <td><a href="/osusume/categories/<%= obj.id %>/edit">編集</a></td>
    <td><%= link_to '削除', obj, method: :delete, data: { confirm: 'このデータを削除しますか?' } %></td>
  </tr>
  <% end %>
</table>

<%=link_to 'サインアウト', destroy_account_session_path, method: :delete %>

app/views/admin/new.html.erb
<h1>記事作成</h1>

<% if @article.errors.any? %>
<ul>
    <% @article.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @article,:url => {:action => :create} do |form| %>
<table>
    <tr>
    <th>タイトル</th>
    <td><%= form.text_field :title %></td>
    </tr>
    <tr>
    <th>ライター</th>
    <td><%= form.text_field :writer %></td>
    </tr>
    <tr>
    <th>投稿日時</th>
    <td><%= raw sprintf(form.date_select(
								:my_date,
								use_month_numbers: true,
								start_year:        Time.now.year,
								end_year:          Time.now.year+1,
								date_separator: '%s'),
						'年 ', '月 ') + '日' %></td>
    </tr>
    <tr>
    <th>記事内容</th>
    <td><%= form.cktext_area :main %></td>
    </tr>
    <th>紹介文</th>
    <td><%= form.text_area :intro %></td>
    </tr>
    <tr>
    <th>カテゴリー</th>
    <td><%= collection_check_boxes(:article, :category_ids, Category.all, :id, :name) do |b| %>
        <%= b.label { b.check_box + b.text } %>
        　<% end %>
        </td>
    </tr>
    <tr><th>サムネイル</th>
    <td><%= form.file_field :image %></td></tr>
    <tr><th>状態</th>
    <td><%= form.radio_button :status, false, :checked => "checked" %>下書き<%= form.radio_button :status, true %>公開</td></tr>
  <tr><th></th>
    <td><%= form.submit "送信" %></td></tr>
</table>
<% end %>

app/views/admin/show.html.erb
<div id="preview">
    <h1>プレビューです:<a href="/osusume/admin/<%= @article.id %>/edit">編集する</a></h1>
    <h3>状態：<% if @article.status == true %>公開<% else %>下書き<% end %></h3>
    <h1><a href="/osusume/admin/">もどる</a></h1>
</div>
<% provide(:title, "SHOW") %>

<div id="osusume">

  <div id="main2">
    <div id="dArticle">
      <div id="samune"><%= image_tag @article.image.to_s , :size => '400x250' %></div>
      <div id="mini">
       <p id ="date"><%= @article.my_date.to_date %></p>
       <p id="writer">writer:<%= @article.writer %></p>
       <h1 id="title"><%= @article.title %></h1>
       <% @article.categories.each do |c| %>
          <p id="category"><%= c.name %></p>
        <% end %>
        <div class="box24"><p><%= @article.intro %></p></div>
      </div>
      <div class="clear"></div>
      <div id="articleMain"<p><%= @article.main.html_safe %></p></div>
      <a href="/osusume/admin" class="square_btn">戻る</a>
    </div>
  </div>
  <div class="clear"></div>

app/views/categories/_form.html.erb
<% if category.errors.any? %>
<ul>
    <% category.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
</ul>
<% end %>

<%= form_for category do |form| %>
<table>
  <tr><th>カテゴリ名</th>
    <td><%= form.text_field :name %></td>
  <tr><th></th>
    <td><%= form.submit "送信" %></td></tr>
</table>
<% end %>

app/views/categories/edit.html.erb
<h1>カテゴリ編集</h1>
<%= render 'form', category:@category %>

app/views/categories/new.html.erb
<h1>カテゴリ新規作成</h1>
<%= render 'form', category:@category %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おすまる</title>
    <%= csrf_meta_tags %>
    <meta name="keywords" content="マルチVRゲーム,おすすめ,VR,マルチ,ゲーム,紹介,プロンティアットVR,おすまる">
    <meta name="description" content="マルチVRゲームのおすすめを紹介するサイトです！！　同志社ローム記念館プロジェクト　プロンティアットVR">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

<body>
  <header>
     <p><a href="/osusume/top"><%= image_tag 'logo.png' %></a></p>
  </header>
    <%= yield %>
    <footer>
        <a href="http://www.prontiatvr.com/"><p id="hpLink">◀プロンティアットVR　公式HP</p></a><br>
        <p id="tyosaku">©2018 ProntiatVR
        </p>
        <div id="clear"></div>
    </footer>
  </body>
</html>

app/views/top/index.html.erb
<% provide(:title, "TOP") %>

<%= image_tag 'header.png' , :id => 'multi'%>
<%= image_tag 'mobile_header.png' , :id => 'mobile_multi'%>


<div id="osusume">
  <div id="aside">
    <h2>最新の記事</h2>
    <% @articles.each do |obj| %>
      <% if obj.status == true %>
        <a href="/osusume/top/<%= obj.id %>"><p id="new"><%= obj.title %></p></a>
      <% end %>
    <% end %>
    <h2 id='category'>カテゴリ一覧</h2>
    <% @categories.each do |obj| %>
      <p id="category"><%= obj.name %></p>
    <% end %>
  </div>
  <!-- スマホ用の最新の記事 -->
  <div id="aside2">
    <h2>最新の記事</h2>
  </div>

  <div id="main"><!---パソコン用記事-->
    <% @articles.each do |obj| %>
      <% if obj.status == true %>
        <div id= "article">
          <a href="/osusume/top/<%= obj.id %>"><%= image_tag obj.image.to_s, :size => '100x150' , :id => 'arImg' %></a></br>

          <div id="content">
            <p id="date"><%= obj.my_date.to_date %></p></br>
            <div class="clear"></div>
            <a href="/osusume/top/<%= obj.id %>" id="title"><h2 id="title"><%= obj.title %></h2></a>
             <% obj.categories.each do |c| %>
                <p id="category"><%= c.name %></p>
              <% end %>
            <a href="/osusume/top/<%= obj.id %>" id="intro"><p id="intro"><%= obj.intro %></p></a>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>

  <div id="mobile_main"><!---スマホ用記事-->
    <% @articles.each do |obj| %>
      <% if obj.status == true %>
        <div id= "mobile_article">
          <a href="/osusume/top/<%= obj.id %>" id="image"><%= image_tag obj.image.to_s, :size => '100x150' , :id => 'arImg' %></a></br>

          <div id="mobile_content">
            <div id="mobile_right">
              <p id="mobile_date"><%= obj.my_date.to_date %></p><br>
              <% obj.categories.each do |c| %>
              <p id="mobile_category"><%= c.name %></p>
              <% end %><br>
              <a href="/osusume/top/<%= obj.id %>" id="mobile_title"><h2 id="mobile_title"><%= obj.title %></h2></a>
            </div>
            <div class="clear"></div>
            <a href="/osusume/top/<%= obj.id %>"><p id="mobile_intro"><%= obj.intro %></p></a>
          </div>

          <hr>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="clear"></div>
</div>

app/views/top/show.html.erb
<% provide(:title, "SHOW") %>

<div id="osusume">
    <div id="aside">
    <h2>最新の記事</h2>
    <% @articles.each do |obj| %>
      <% if obj.status == true %>
        <a href="/osusume/top/<%= obj.id %>"><p id="new"><%= obj.title %></p></a>
      <% end %>
    <% end %>
    <h2 id='category'>カテゴリ一覧</h2>
    <% @categories.each do |obj| %>
      <p id="category"><%= obj.name %></p>
    <% end %>
  </div>

  <div id="main2">
    <div id="dArticle">
      <div id="samune"><%= image_tag @article.image.to_s , :size => '400x250' %></div>
      <div id="mini">
       <p id ="date"><%= @article.my_date.to_date %></p>
       <p id="writer">writer:<%= @article.writer %></p>
       <h1 id="title"><%= @article.title %></h1>
       <% @article.categories.each do |c| %>
          <p id="category"><%= c.name %></p>
        <% end %>
        <div class="box24"><p><%= @article.intro %></p></div>
      </div>
      <div class="clear"></div>
      <div id="articleMain"<p><%= @article.main.html_safe %></p></div>
      <a href="/osusume/top/index" class="square_btn">戻る</a>
    </div>
  </div>
  <div class="clear"></div>

<!--
<div class="clear"></div>
--->

  <div id="mobile_main2" class="clerafix">
    <p id ="date2"><%= @article.my_date.to_date %></p>
    <p id="writer2">writer:<%= @article.writer %></p>
    <div id="headline" class="clearfix">
      <div id="samune2"><%= image_tag @article.image.to_s , :size => '160x160' %></div>
      <div id="title_category">
        <h1 id="title2"><%= @article.title %></h1>
        <% @article.categories.each do |c| %>
          <p id="category2"><%= c.name %></p>
        <% end %>
      </div>
    </div>
    <div class="clear"></div>
    <div class="box24"><p><%= @article.intro %></p></div>
    <div id="articleMain2"<p><%= @article.main.html_safe %></p></div>
    <a href="/osusume/top/index" class="square_btn">戻る</a>
  </div>

</div>